#! /bin/bash
# /etc/init.d/alarmSystem 

### BEGIN INIT INFO
# Provides:          alarmSystem
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start a program at boot
# Description:       A simple script from www.stuffaboutcode.com which will start / stop a program a boot / shutdown.
### END INIT INFO

# If you want a command to always run, put it here
echo "init.d script"
# Carry out specific functions when asked to by the system
statusfunction(){
	python /home/pi/RPIHomeAlarmSystem/rpihomealarmsystem/alarm_remote.py -p
}

is_running(){
    if ps aux | grep "[a]larm_system"
    then
        return 0
    else
        return 1
    fi
}

starting(){
	echo "verifying if user alarm_config is in user home directory"
	if [ -e /mnt/dropbox/Workspace/alarm_config.yaml ]; then
		echo "user alarm_config.yaml file was found"
	else
        if [ -e /home/pi/alarm_config.json ]; then
            echo "user alarm_config.json file was found"
        else
            exit 1
        fi
    fi

	# Check if alarm_system is running
	if is_running
	then
		echo "Already running..."
	else
		echo "Starting alarmSystem"
		cd /home/pi/RPIHomeAlarmSystem/rpihomealarmsystem/ && exec python -u /home/pi/RPIHomeAlarmSystem/rpihomealarmsystem/alarm_system.py 1>&1 2>&1 &
	fi
}

stopping(){
    # kill application you want to stop
    if is_running
    then
        echo "killing other alarm processes"
	    pkill -f alarm_system
	else
	    echo "alarmSystem not running"
	fi
}

updating(){
    #echo "Updating Pydispatcher thread safe from dropbox version"
	#/home/pi/Alarm_system_v1.0/PyDispatcher-2.0.1ts/setup.py install

    echo "synching /home/pi/ directory with latest version from dropbox"
	# TODO corriger mount -a qui ne fait pas la job
	mount -a
	rsync -av --delete /mnt/dropbox/Workspace/RPIHomeAlarmSystem /home/pi/

    if [ -e /mnt/dropbox/Workspace/alarm_config.yaml ]; then
		rsync -av --delete /mnt/dropbox/Workspace/alarm_config.yaml /home/pi/alarm_config.yaml
	fi
	if [ -e /mnt/dropbox/Workspace/alarm_config.json ]; then
		rsync -av --delete /mnt/dropbox/Workspace/alarm_config.json /home/pi/alarm_config.json
	fi
}

case "$1" in
  start)
	starting
    ;;
  update)
    if is_running
	then
	    stopping
	    updating
	    starting
	else
	    updating
	fi

    ;;
  stop)
	stopping
    ;;
  restart)
	stopping
	starting
    ;;
  status)
	statusfunction
	;;
  arm)
	python /home/pi/RPIHomeAlarmSystem/rpihomealarmsystem/alarm_remote.py -s StateArmed
	statusfunction
	;;
  dearm)
    python /home/pi/RPIHomeAlarmSystem/rpihomealarmsystem/alarm_remote.py -s StateIdle
    statusfunction
	;;
  *)
    echo "Usage: /etc/init.d/alarmSystem {start|stop|restart|update|status|arm|dearm}"
    exit 1
    ;;
esac

exit 0
